#Allowed Values: NONE, SCROLL, TOGGLE, BOTH
smoothType = "BOTH"
#Allowed Values: DOUBLE_TAP_ON, DOUBLE_TAP_OFF, DOUBLE_TAP_ON_OFF, TAP_ON_OFF, DISABLE
toggleType = "DOUBLE_TAP_ON"
#Allowed Values: NONE, SCALED, SET
mouseSensitivityMod = "NONE"
scrollWhenToggled = false
sartAtMaxZoom = false
#Range: 0 ~ 10
mouseSensitvityReduction = 5
#Range: 1 ~ 20
scrollZoomSpeed = 12
#Range: 1 ~ 100
maxZoom = 50

