
[tools]

	[tools.3x3]
		#The multiplier for the area tools durability.
		#The durability is calculated by the equivalant tools durability
		#multiplied by this multiplier
		#Default: 5.0
		#Range: 1.0 ~ 15.0
		multiplier = 5.0
		#The modifier for the speed of area tools
		#The speed gets divided by this number, so the higher the number, the slower the tool
		#Default: 4
		#Range: 1.0 ~ 10.0
		speed_modifier = 3.5

	[tools.swapping]
		#The blacklisted blocks
		blacklist = "minecraft:bedrock"
		#Maximum hardness that can be swapped
		#Range: 0.0 ~ 1.7976931348623157E308
		max_hardness = 49.0

	[tools.magnet]
		#How often the magnet needs to check to magnetize, in ticks
		#default: 1
		#Range: 1 ~ 60
		tick_rate = 1
		#The radius (cube) that items can be magnetized
		#default: 6
		#Range: 1 ~ 16
		radius = 6
		#Should the magnet only pickup items that fit into the inventory
		#default: true
		pick_up = true
		#The strength of the magnet.
		#default: 0.7
		#Range: 0.1 ~ 5.0
		strength = 0.7

	[tools.wateringCans]
		#Can the watering cans spread grass faster
		canSpreadGrass = true
		#The refill rate of water/tick
		#Range: 1 ~ 100000
		refillRate = 30
		#Moisterize farm land
		moisterize = true

		[tools.wateringCans.basic]
			#The radius of effect for the watering can
			#Number MUST be uneven
			#Range: 1 ~ 15
			radius = 3
			#Use water at all, or have it be infinite use
			#Default: true
			useWater = true
			#Auto harvest fully grown crops
			#Default: false
			autoHarvest = false
			#The maximum amount of water the watering can can hold
			#Range: 100 ~ 100000
			maxWater = 1000
			#The amount of water consumed per tick
			#Range: 1 ~ 10000
			drainRate = 5
			#The chance to further a growth stage
			#Range: 1 ~ 100
			chance = 10

		[tools.wateringCans.copper]
			#The radius of effect for the watering can
			#Number MUST be uneven
			#Range: 1 ~ 15
			radius = 3
			#Use water at all, or have it be infinite use
			#Default: true
			useWater = true
			#Auto harvest fully grown crops
			#Default: false
			autoHarvest = false
			#The maximum amount of water the watering can can hold
			#Range: 100 ~ 100000
			maxWater = 2000
			#The amount of water consumed per tick
			#Range: 1 ~ 10000
			drainRate = 5
			#The chance to further a growth stage
			#Range: 1 ~ 100
			chance = 15

		[tools.wateringCans.quartz]
			#The radius of effect for the watering can
			#Number MUST be uneven
			#Range: 1 ~ 15
			radius = 3
			#Use water at all, or have it be infinite use
			#Default: true
			useWater = true
			#Auto harvest fully grown crops
			#Default: false
			autoHarvest = false
			#The maximum amount of water the watering can can hold
			#Range: 100 ~ 100000
			maxWater = 5000
			#The amount of water consumed per tick
			#Range: 1 ~ 10000
			drainRate = 5
			#The chance to further a growth stage
			#Range: 1 ~ 100
			chance = 25

		[tools.wateringCans.diamond]
			#The radius of effect for the watering can
			#Number MUST be uneven
			#Range: 1 ~ 15
			radius = 5
			#Use water at all, or have it be infinite use
			#Default: true
			useWater = true
			#Auto harvest fully grown crops
			#Default: false
			autoHarvest = false
			#The maximum amount of water the watering can can hold
			#Range: 100 ~ 100000
			maxWater = 10000
			#The amount of water consumed per tick
			#Range: 1 ~ 10000
			drainRate = 5
			#The chance to further a growth stage
			#Range: 1 ~ 100
			chance = 35

		[tools.wateringCans.ender]
			#The radius of effect for the watering can
			#Number MUST be uneven
			#Range: 1 ~ 15
			radius = 7
			#Use water at all, or have it be infinite use
			#Default: false
			useWater = false
			#Auto harvest fully grown crops
			#Default: true
			autoHarvest = true
			#The maximum amount of water the watering can can hold
			#Range: 100 ~ 100000
			maxWater = 10000
			#The amount of water consumed per tick
			#Range: 1 ~ 10000
			drainRate = 5
			#The chance to further a growth stage
			#Range: 1 ~ 100
			chance = 50

